version: 2
updates:
  # Waiting on https://github.com/dependabot/dependabot-core/issues/8166
  # - package-ecosystem: zig
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #     time: "08:00"
  #   labels:
  #     - "dependencies"
  #   commit-message:
  #     prefix: "chore"
  #     include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
