# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: example

# Actually builds the binaries.
builds:
  - builder: zig
    flags:
      - -Doptimize=ReleaseSafe
      - -Dgit_commit={{ .Commit }}
      - -Dversion={{ .Version }}
      - -Ddate={{ .Date }}
    targets:
      - x86_64-linux
      - x86_64-windows
      - aarch64-linux
      - x86_64-macos
      - aarch64-macos

# Creates archives for each target.
archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

# Changelog configuration (will be in the github release).
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# A footer to add to all releases.
release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

# Creates Linux packages.
nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    maintainer: Carlos Alexandro Becker <carlos@becker.software>
    formats:
      - deb
      - apk
      - rpm

# Creates Darwin universal binaries.
universal_binaries:
  - replace: true

# Enables source archives.
source:
  enabled: true

# SBOMs for the archives.
sboms:
  - artifacts: archive

# Sign binaries with cosign.
signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

# Create Docker images.
dockers_v2:
  - images:
      - "ghcr.io/goreleaser/example-zig"
    tags:
      - "{{ .Tag }}"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

# Sign the Docker images with cosign as well.
docker_signs:
  - cmd: cosign
    args:
      - "sign"
      - "${artifact}"
      - "--yes"

# Sets up homebrew-taps.
# PS: this will require a personal access token, as it is cross-repository.
homebrew_casks:
  - repository:
      owner: goreleaser
      name: example-homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    homepage: https://goreleaser.com
    description: Example zig release.
    license: MIT
    # usually you don't need to set this, we do to prevent conflicts with other
    # example-* repositories
    name: example-zig
